
cmake \
  -DCMAKE_PREFIX_PATH:PATH=${PREFIX} \
  -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release \
  -DHIGHFIVE_UNIT_TESTS=ON \
  -DHIGHFIVE_EXAMPLES=OFF \
  -DHIGHFIVE_UNIT_TESTS=OFF \
  .

make install
