{% set name = "HighFive" %}
{% set version = "2.2.1" %}
{% set sha256 = "964c722ba916259209083564405ef9ce073b15e9412955fef9281576ea9c5b85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BlueBrain/HighFive/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  run:
    - hdf5

test:
  commands:
    # Testing for installation of headers - non-exhaustive list.
    - test -d $PREFIX/include/highfive  # [unix]
    - test -f $PREFIX/include/highfive/H5Attribute.hpp  # [unix]
    - test -d $PREFIX/include/highfive/bits  # [unix]
    - test -f $PREFIX/include/highfive/bits/H5File_misc.hpp  # [unix]
    - test -f $PREFIX/include/highfive/H5Exception.hpp  # [unix]
    - test -f $PREFIX/share/HighFive/CMake/HighFiveConfig.cmake  # [unix]
    - test -f $PREFIX/share/HighFive/CMake/HighFiveTargets.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\highfive\H5Attribute.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\highfive\bits\H5File_misc.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\highfive\H5Exception.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\share\HighFive\CMake\HighFiveConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\share\HighFive\CMake\HighFiveTargets.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/BlueBrain/HighFive
  license: BSL-1.0
  license_file: LICENSE
  summary: Header-only C++ HDF5 interface
  description: HighFive is a modern C++/C++11 friendly interface for libhdf5.
  dev_url: https://github.com/BlueBrain/HighFive

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - ferdonline
    - tdegeus
