{% set name = "HighFive" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/highfive-devs/HighFive/archive/v{{ version }}.tar.gz
  sha256: 622034f34badda41255d7793e1c5a3046954dcf0875b0bca076e7c77088a8890

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - hdf5

test:
  commands:
    # Testing for installation of headers - non-exhaustive list.
    - test -d $PREFIX/include/highfive  # [unix]
    - test -f $PREFIX/include/highfive/H5Attribute.hpp  # [unix]
    - test -d $PREFIX/include/highfive/bits  # [unix]
    - test -f $PREFIX/include/highfive/bits/H5File_misc.hpp  # [unix]
    - test -f $PREFIX/include/highfive/H5Exception.hpp  # [unix]
    - test -f $PREFIX/lib/cmake/HighFive/HighFiveConfig.cmake  # [unix]
    - test -f $PREFIX/lib/cmake/HighFive/HighFiveTargets.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\highfive\H5Attribute.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\highfive\bits\H5File_misc.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\highfive\H5Exception.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\HighFive\HighFiveConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\HighFive\HighFiveTargets.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/highfive-devs/HighFive
  license: BSL-1.0
  license_file: LICENSE
  summary: Header-only C++ HDF5 interface
  description: HighFive is a modern C++/C++14 friendly interface for libhdf5.
  dev_url: https://github.com/highfive-devs/HighFive

extra:
  recipe-maintainers:
    - theAeon
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - ferdonline
    - tdegeus
